sudo: required

language: c

env:
  global:
    - GAPCONTAINER="gapsystem/gap-docker-stable-4.11"
    - GAPDIRNAME="gap-stable-4.11"

  matrix:
    - PKG_NAME=ace
    - PKG_NAME=aclib
    - PKG_NAME=alnuth
    - PKG_NAME=anupq
    - PKG_NAME=autodoc
    - PKG_NAME=automata
    - PKG_NAME=automgrp
    - PKG_NAME=autpgrp
    - PKG_NAME=carat
    - PKG_NAME=circle
    - PKG_NAME=cohomolo
    - PKG_NAME=congruence
    - PKG_NAME=crime
    - PKG_NAME=crisp
    - PKG_NAME=crypting
    - PKG_NAME=cryst
    - PKG_NAME=crystcat
    - PKG_NAME=cubefree
    - PKG_NAME=curlinterface
    - PKG_NAME=cvec
    - PKG_NAME=datastructures
    - PKG_NAME=deepthought
    - PKG_NAME=design
    - PKG_NAME=digraphs
    - PKG_NAME=edim
    - PKG_NAME=example
    - PKG_NAME=factint
    - PKG_NAME=fga
    - PKG_NAME=fining
    - PKG_NAME=float
    - PKG_NAME=format
    - PKG_NAME=forms
    - PKG_NAME=fplsa
    - PKG_NAME=francy
    - PKG_NAME=genss
    - PKG_NAME=grape
    - PKG_NAME=grpconst
    - PKG_NAME=guarana
    - PKG_NAME=guava
    - PKG_NAME=hap
    - PKG_NAME=hecke
    - PKG_NAME=help
    - PKG_NAME=idrel
    - PKG_NAME=io
    - PKG_NAME=irredsol
    - PKG_NAME=json
    - PKG_NAME=jupyterkernel
    - PKG_NAME=jupyterviz
    - PKG_NAME=kan
    - PKG_NAME=kbmag
    - PKG_NAME=laguna
    - PKG_NAME=liealgdb
    - PKG_NAME=liepring
    - PKG_NAME=liering
    - PKG_NAME=loops
    - PKG_NAME=lpres
    - PKG_NAME=majoranaalgebras
    - PKG_NAME=mapclass
    - PKG_NAME=matgrp
    - PKG_NAME=modisom
    - PKG_NAME=monoidalcategories
    - PKG_NAME=normalizinterface
    - PKG_NAME=nq
    - PKG_NAME=numericalsgps
    - PKG_NAME=openmath
    - PKG_NAME=orb
    - PKG_NAME=patternclass
    - PKG_NAME=permut
    - PKG_NAME=polenta
    - PKG_NAME=polycyclic
    - PKG_NAME=primgrp
    - PKG_NAME=profiling
    - PKG_NAME=qpa
    - PKG_NAME=radiroot
    - PKG_NAME=rds
    - PKG_NAME=repsn
    - PKG_NAME=resclasses
    - PKG_NAME=scscp
    - PKG_NAME=semigroups
    - PKG_NAME=sglppow
    - PKG_NAME=sgpviz
    - PKG_NAME=simpcomp
    - PKG_NAME=singular
    - PKG_NAME=smallgrp
    - PKG_NAME=smallsemi
    - PKG_NAME=sonata
    - PKG_NAME=sophus
    - PKG_NAME=spinsym
    - PKG_NAME=thelma
    - PKG_NAME=tomlib
    - PKG_NAME=toric
    - PKG_NAME=transgrp
    - PKG_NAME=unipot
    - PKG_NAME=unitlib
    - PKG_NAME=utils
    - PKG_NAME=uuid
    - PKG_NAME=walrus
    - PKG_NAME=wedderga
    - PKG_NAME=xmod
    - PKG_NAME=xmodalg
    - PKG_NAME=yangbaxter
    - PKG_NAME=zeromqinterface

services:
  - docker

before_install:
- docker pull ${GAPCONTAINER}

script:
    - docker version
    - docker run -v $PWD:/home/gap/travis/ ${GAPCONTAINER} /bin/sh -c "GAPDIRNAME=${GAPDIRNAME} PKG_NAME=${PKG_NAME} TERM=xterm LANG=en_GB.UTF-8 /home/gap/travis/ci.sh"
